name: football-stats-profile
channels:
  - defaults
  - conda-forge
dependencies:
  - jupyter=1.0.0
  - scikit-learn=0.24.2
  - pandas=1.3.1
  - matplotlib=3.4.2
  - pip=21.2.4
  - black=19.10
  - python=3.9.5
